baseURL = 'https://ugoforlimpopoli.org'
defaultContentLanguage = 'it'
locale = 'it-IT'
title = 'UGO Aula Studio'

[markup]
[markup.goldmark]
[markup.goldmark.parser]
autoHeadingID = true
autoHeadingIDType = 'github'

[markup.goldmark.parser.attribute]
block = true

[menu]
[[menu.main]]
name = "Home"
url = "/"
weight = 10
[[menu.main]]
name = "About"
url = "/about/"
weight = 20
[[menu.main]]
name = "Moduli"
url = "/first-timers/"
weight = 20

[privacy]
[privacy.disqus]
disable = true
[privacy.googleAnalytics]
disable = true
[privacy.instagram]
disable = true
[privacy.x]
disable = true
[privacy.vimeo]
disable = true
[privacy.youtube]
disable = true

[outputs]
section = ["HTML"]

[params]
logo = "/images/ugo-logo.png"
